# Generated by Django 5.2.1 on 2025-05-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_delete_laptops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
